// Generated by Wrangler on Tue Jun 11 2024 15:21:35 GMT+0900 (日本標準時)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STRIPE_SECRET_API_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: Ai;
}
